language: Go
go:
    - 1.5.4
    - 1.6.3
    - 1.7
    - tip
matrix:
    include:
        - go: 1.4.3
          script:
              - go get -t -v ./...
              - go test -v -race ./...
         - arch: ppc64le
           go: 1.5.4
           script:
              - go get -t -v ./...
              - diff -u <(echo -n) <(gofmt -d -s .)
              - go tool vet .
         - arch: ppc64le
           go: 1.7
           script:
              - go get -t -v ./...
              - diff -u <(echo -n) <(gofmt -d -s .)
              - go tool vet .
          - arch: ppc64le
           go: tip
           script:
              - go get -t -v ./...
              - diff -u <(echo -n) <(gofmt -d -s .)
              - go vet .
              - go test -v -race ./...
    allow_failures:
        - go: tip
    exclude:
        - arch: ppc64le
          go: 1.6.3
    fast_finish: true
install:
    - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
    - go get -t -v ./...
    - diff -u <(echo -n) <(gofmt -d -s .)
    - go tool vet .
    - go test -v -race ./...
